name: PROD용 S3에 업로드 및 CLOUDFRONT 초기화

on:
  push:
    branches:
      - ICC-110-main-branch-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2에 SSH 접속 후 배포
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/client
            git pull origin main
            npm install
            npm run build

            echo "======[BEFORE S3 SYNC]====="
            echo "[ENV] AWS_PROFILE: $AWS_PROFILE"
            echo "[ENV] AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
            echo "[ENV] AWS config files:"
            ls -al ~/.aws || echo "No ~/.aws directory"
            cat ~/.aws/credentials || echo "No credentials file"
            aws sts get-caller-identity || echo "Unable to get caller identity"

            echo "[ACTION] Running aws s3 sync..."
            aws s3 sync ./dist ${{ secrets.S3_URL }} --delete || echo "S3 sync failed"

            echo "======[AFTER S3 SYNC / BEFORE CLOUDFRONT]====="
            aws sts get-caller-identity || echo "Unable to get caller identity"

            echo "[ACTION] Writing new credentials file for CloudFront"
            mkdir -p ~/.aws
            cat > ~/.aws/credentials <<EOL
            [default]
            aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
            aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
            region=${{ secrets.AWS_REGION_PROD }}
            EOL

            echo "[ENV] AWS_ACCESS_KEY_ID after setting credentials:"
            echo $AWS_ACCESS_KEY_ID
            echo "credentials file after write:"
            cat ~/.aws/credentials

            echo "[ACTION] Invalidating CloudFront cache..."
            aws cloudfront create-invalidation \
              --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} \
              --paths "/*"