name: PROD용 S3 업로드 및 CloudFront 초기화

on:
  push:
    branches:
      - ICC-110-main-branch-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub 코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 의존성 설치 및 빌드
        run: |
          cd client
          npm install
          npm run build

      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ secrets.AWS_REGION_PROD }}

      - name: S3에 업로드
        run: |
          aws s3 sync ./dist ${{ secrets.S3_URL }} --delete
      - name: CloudFront 초기화
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} \
            --paths "/*"
