name: PROD용 S3에 업로드 및 CLOUDFRONT 초기화

on:
  push:
    branches:
      - ICC-110-main-branch-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub 코드 체크아웃
        uses: actions/checkout@v4
        
      - name: AWS 로그인
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{ secrets.AWS_REGION_PROD }}

      - name: EC2에 SSH 접속 후 빌드, S3 업로드
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }} 
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/client
            git pull origin main
            npm install
            npm run build

            # S3 업로드
            aws s3 sync ./dist ${{ secrets.S3_URL }} --delete

      - name: CloudFront 초기화
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} \
            --paths "/*"
